version: '2'
services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./etc/localtime:/etc/localtime
    network_mode: "bridge"
    links:
      - php_fpm:php-fpm
    depends_on:
      - php_fpm
    environment:
      TZ: 'Asia/Shanghai'
  php_fpm:
    image: "heyw/php-xdebug:latest"
    volumes:
      - ../app/web:/app/web
      - ./etc/localtime:/etc/localtime
      - ./etc/php-fpm:/usr/local/etc
    network_mode: "bridge"
    depends_on:
      - redis
      - mysql
      - memcached
    links:
      - redis:redis
      - mysql:mysql
      - memcached:memcached
  memcached:
    image: "memcached:latest"
    network_mode: "bridge"
    mem_limit: 128M
    command: memcached -m 128M
  redis:
    image: "redis:4"
    ports:
      - "6379:6379"
    volumes:
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    network_mode: "bridge"
    command: "redis-server /usr/local/etc/redis/redis.conf"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql-data:/var/lib/mysql
      - ./etc/localtime:/etc/localtime
      - ./etc/mysql/my.cnf:/etc/my.cnf
    network_mode: "bridge"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.2"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ../data/es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    network_mode: "bridge"     